# Generated by Django 6.0.1 on 2026-02-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('color', 'Colors'), ('colorType', 'Color Types'), ('disposition', 'Dispositions'), ('shape', 'Shapes'), ('human', 'Humans'), ('animal', 'Animals'), ('landscape', 'Environments'), ('vehicules', 'Vehicles'), ('object', 'Objects'), ('style', 'Styles')], default='custom', max_length=50),
        ),
    ]
