# Generated by Django 6.0.1 on 2026-05-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_add_submitted_by_to_album'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='source_type',
            field=models.CharField(blank=True, choices=[('deezer', 'Deezer'), ('discogs', 'Discogs'), ('bandcamp', 'Bandcamp')], max_length=20),
        ),
        migrations.AddField(
            model_name='album',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_type',
            field=models.CharField(blank=True, choices=[('deezer', 'Deezer'), ('discogs', 'Discogs'), ('bandcamp', 'Bandcamp')], max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='albums.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='albums.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
