# Generated by Django 6.0.1 on 2026-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_source_type_album_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='source_type',
            field=models.CharField(blank=True, choices=[('deezer', 'Deezer'), ('discogs', 'Discogs'), ('bandcamp', 'Bandcamp'), ('rateyourmusic', 'RateYourMusic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source_type',
            field=models.CharField(blank=True, choices=[('deezer', 'Deezer'), ('discogs', 'Discogs'), ('bandcamp', 'Bandcamp'), ('rateyourmusic', 'RateYourMusic')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
